"""Add Constaints to BaseDonation model

Revision ID: 8989ace5923b
Revises: 0205e59c4aef
Create Date: 2025-02-04 17:48:25.596866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8989ace5923b'
down_revision = '0205e59c4aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
