DEFAULT_APP_TITLE = 'QRKot'
DEFAULT_APP_DESCRIPTION = 'Благотворительный фонд поддержки котиков QRKot'
DEFAULT_DATABASE_URL = 'sqlite+aiosqlite:///./fastapi.db'
DEFAULT_SECRET = 'SECRET'
SESSION_LIFETIME = 3600
PROJECT_NAME_FIELD_MIN_LENGTH = 1
PROJECT_NAME_FIELD_MAX_LENGTH = 100
PROJECT_DESCRIPTION_FIELD_MIN_LENGTH = 1